# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('dineout', 'Dineout'), ('delivery', 'Delivery')], default='cafe', max_length=10),
        ),
    ]
