# Generated by Django 2.1.3 on 2019-05-31 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20181201_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='price_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
